### ISSUE TITLE
Learn about Active Transportation's project tracking workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#17]
Point of contact: Nathan W. 
Have already done a lot of research on ATSD's workflow, but this is a placeholder for circling back after speaking with other divisions if necessary. 

Ask Nathan about the following:
- Public Work datasets (sidewalks, safe schools, etc.)

**Comment by zappfyllc** [comment]
Had to reschedule with Nathan because I didn't have enough time to evaluate the Interim Project Database before meeting with him and I didn't want to waste his time on that front. We will reschedule for next sprint, as Nathan is out all next week.

**Comment by zappfyllc** [comment]
We will either remove this from the Epic for research and restructure what it says to fit the conversation I should have with Nathan, or I will schedule a call with Nathan in this sprint to focus on requirements for Active Transportation & Street Division specifically.

**Comment by zappfyllc** [comment]
Call scheduled for next sprint: 1/31. Will update with notes when done.

**Comment by zappfyllc** [comment]
Call with Nathan on 1/31: https://docs.google.com/document/d/13DEDFInSEhpNgCs6EG0wXXc-PLfRBtCMmoitWGS1yC4/edit?usp=sharing

**Comment by zappfyllc** [comment]
Added to synthesis document: https://docs.google.com/document/d/1swkNIccJtT5IzdQz_zi4H2LgzhQd3c4iC22Y8SiGOQk/edit?usp=sharing
