### ISSUE TITLE
Learn about Transportation Engineering's project tracking workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#18]
@zappfyllc will meet with Manuel G on 10/9. They sent over [these docs](https://drive.google.com/open?id=1-oAse6ekwH6KbLw2Aj3Oau_zix8Z48_h) in advance.

**Comment by zappfyllc** [comment]
Meeting Notes for 2019-10-09 call with Amica and Manuel: https://docs.google.com/document/d/1oB90vc_A-BsxL6jl37PfFRI5UCct5SIi0fF3swPqghk/edit?usp=sharing

Action Items for JD:
- Log data entities relevant to TED in overall analysis for developing ERDs
- Identify system features for TED use cases and detail TED use cases to start
