### ISSUE TITLE
Learn about Transit Enhancement's project tracking workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#19]
Transit Enhancement: Manages infrastructure projects aimed at improving transit speed and reliability. Examples include the new shared bus/bike lane on West 5th St and the Guadalupe contraflow project between 15th and MLK streets downtown. In the future it may include more policy work, but currently most of my time is spent managing small (ex: adjusting roadway striping) and larger (ex: installing a new bus lane) capital projects for the benefit of transit. Hope that helps.

Currently tracking projects with Excel, Microsoft Projects, and Word. [Examples here](https://drive.google.com/open?id=18BSbHmwZZ7u91PbLiHZEZS4EPI_unYMq). 

Point of contact: Caitlin D.

**Comment by amenity** [comment]
@zappfyllc - please review; determine whether we should meet with TE, pass along specific questions, etc.

**Comment by zappfyllc** [comment]
I will look over the documents Caitlin sent over from 10/29 and then schedule a user interview with her in this sprint.

**Comment by zappfyllc** [comment]
Initial Research findings from documents sent over: https://docs.google.com/document/d/1cjaWCXYoawfm5j_5TaaFazHk9cnsEXfc7hVGKFhrmXk/edit?usp=sharing

I will add meeting notes here if we do end up meeting. I sent an email to Caitlin and will try to schedule with her ASAP to clarify some of the questions I have, which mostly involve the project schedule PDF she sent over (the word document and spreadsheet are self-explanatory).

**Comment by zappfyllc** [comment]
Agreed with @amenity to postpone for now instead of badgering for a response. Moving this to the Backlog for now.

**Comment by zappfyllc** [comment]
Meeting scheduled for 2/5 at 1 PM. Will update with notes and add to requirements analysis document after the meeting and then will reclose issue.

**Comment by zappfyllc** [comment]
Meeting Notes: https://docs.google.com/document/d/1cjaWCXYoawfm5j_5TaaFazHk9cnsEXfc7hVGKFhrmXk/edit?usp=sharing

**Comment by zappfyllc** [comment]
Added to synthesis document: https://docs.google.com/document/d/1swkNIccJtT5IzdQz_zi4H2LgzhQd3c4iC22Y8SiGOQk/edit?usp=sharing
