### ISSUE TITLE
Learn about Vision Zero's project tracking workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#21]
Lewis L. & Joel

https://austintexas.gov/visionzero

**Comment by zappfyllc** [comment]
Scheduled a call with Lewis and Joel for Friday, 10/25 2-3

**Comment by zappfyllc** [comment]
Notes from Initial Call (10/25) with Lewis: https://docs.google.com/document/d/1peahuEIcRvdOzZnOFf7jOnMiMZFjUs1duRK83TIralY/edit?usp=sharing
