### ISSUE TITLE
Learn about Arterial Management's project tracking workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#23]
Jen D., Brian C.,

**Comment by zappfyllc** [comment]
Scheduled session for 10/22 from 3-4

**Comment by zappfyllc** [comment]
Session Notes: https://docs.google.com/document/d/1JmcGIUp2Sc5BtmP76-19LavE4MsQIlMNN9eL6MQuR18/edit?usp=sharing

Action Items for JD:

- Follow-up with Jen on additional documentation and sharing Knack application (Data Tracker) if she doesn't
- Clarify questions on additional documentation/Knack (see above)
- Update feature set and data entity log according to initial research
