### ISSUE TITLE
Research current ATD project tracking workflows

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#25]
- Perform user interviews
- Review documents/tools
- Add into [ATD MPD Learnings Synthesis document](https://docs.google.com/document/d/1swkNIccJtT5IzdQz_zi4H2LgzhQd3c4iC22Y8SiGOQk/edit?usp=sharing)

Notes and documents in [Google Drive](https://drive.google.com/drive/folders/1NYqaRT7IczU3d-vx9PFZKjtvpvxP58f5).

**Comment by zappfyllc** [comment]
ATD project tracking workflows synthesis: https://docs.google.com/document/d/1swkNIccJtT5IzdQz_zi4H2LgzhQd3c4iC22Y8SiGOQk/edit?usp=sharing

The deliverable above should cover all of the issues in this Epic, which involved meeting with various workgroups across the city that have intersections with mobility infrastructure projects. These workgroups are engaged in subsequent sprint reviews and follow-up sessions, but this is the starting point for aggregating the nature of their work, what they may need from the Mobility Project Database, and painpoints they have in dealing with current systems in use.

@amenity @johnclary While this synthesis document is put against success criteria developed earlier in the project, I think some of these findings could be helpful in evaluating all systems on DTS' radar that may be mentioned in the document itself. Additionally, the meeting notes should be organized in a manner that is helpful for insight into day-to-day operations of various teams.
