### ISSUE TITLE
Gather basic Capital Projects Explorer information

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#27]
On October 1, 2019, the City plans to release Capital Projects Explorer (CPE), an online mapping and reporting tool for the Capital Improvements Program (CIP), as a new public resource available for monitoring capital projects (excluding AE). 

- [Staging site](https://austin-bond.projects.socrata.com/projects) (credentials in email)
- [Sharepoint site](https://cityofaustin.sharepoint.com/sites/CPE/SitePages/Contact-Us.aspx)
- [Presentation](https://drive.google.com/drive/folders/1DGklWV25hIRTkIDhH3aaQ6TKRhYRAfeL)

### Questions for CPE team
 - Public reception
   - Are there analytics? 
   - What was the feedback after it was launched for the Mobility Bond?
 - Data
   - Who did the eCapris integration? How? Lessons learned?
   - Is _all_ the CPE data stored and edited in eCapris?
   - How are the geographic features maintained and edited?
   - Data structure

### Question for Nathan
 - Any of these projects in the Access DB? What additional information is stored about them there? 
 - Do you see all of this data being visible in MPD?

**Comment by amenity** [comment]
@johnclary - do you have any other questions about CPE?

**Comment by johnclary** [comment]
thanks @amenity. 

- point of clarification about integration: does eCapris *consume* any external data, or is it only downstreamed to CPE?

- r.e. your point about feedback, if you can press on whether or not their has been public input/research, and/or if there are plans to continue to do so in the future. also, who is the primary audience of the CPE, and do they have analytics/data on this?

**Comment by amenity** [comment]
### Notes from 9/17/19 CPE training meeting at Barton Oaks

- Built with Socrata
- 8th grade reading level, thinking of more comprehensive reporting down the line when drilling down, but keep front simple
- Working iteratively, expect it to evolve; changes after 6 months
- (One-way) pull from eCapris once a month
- Main navigation: toggles & filters - funding, council district

**Funding**
- Each dept uses funding accounts a little differently
- Purchases have subcategory

**User research**
- Thus far, have not done any requirements gathering with users or done outreach; building off of what worked and didn't with initial site, have analytics for that 
- About to perform user-testing
- Going to send out a survey next
- Audiences: 
  - Community stakeholders
  - Businesses that want to do business with the City

**Geography**
- Inconsistency with mapping accross departments, hoping to standardize to improve performance
- Will be trying to move from polygons to points

**Fields**
- **Project location** - not required - was added because people were putting detailed location information in description - some of this is being pulled from eCAPRIS and getting concatenated so it's not useful
- **Budget snapshot** - actual appropriation + planned appropriation; Nathan: this might not ever accurately reflect current budget planning; Going to force conversations b/w program managers and finance and PIOs

**Comment by amenity** [comment]
Feel like I have a good intro grasp on this; am going to set up a call with Morgan B. to learn more about the tech (eCapris integration and GIS) aspects.
