### ISSUE TITLE
Procure Zappfy services

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#28]
- [x] @johnclary submit [non-competitive exemption](https://drive.google.com/open?id=1Y7uS0UVBvQk_TQzFCWSFMlqgqjJpRHZc) — JD/Zappfy has unique specific experience using Knack
- [x] @amenity email JD asking him to
    - Add implementation line items from the Level 1 estimate in his [Discovery Phase Report](https://drive.google.com/drive/folders/13k_dn3u7ccbyNROeDwadZZEWb1F4DwHp), pages 14-15
    - Increase total to $45k with extra as TBD
    - Register as a vendor with the City — [PDF Form](https://cityofaustin.sharepoint.com/sites/FSD/PurchasingCityWide/Shared%20Documents/MemoandForms/vendor_profile.pdf?CT=1566418592331&OR=OWA-NT&CID=9b2219e1-0d99-5e1b-89c4-a1ba79668fb4#search=vendor%20registration) / [Website](https://www.austintexas.gov/financeonline/account_services/account/login.cfm)
- [x] Open Magic ticket to create CTM PR — Scott created HD#1975790 Magic ticket under Peggy's name & assigned the ticket to David Barron.
- [x] Complete CTM Purchase Request — Use funding #: 5610-2400-4200-5260
- [x] CTM Creates Purchase order
- [ ] Payment issued to Zappfy

**Comment by johnclary** [comment]
Proposal and funding numbers have been added to PR. Cert of exemption is waiting for Peggy's signature. Expecting Peggy to submit today.

**Comment by johnclary** [comment]
From David (CTM):
> PR # for this is 31282. Financial review will likely contact you for supporting documentation. (Sole source Documents)

Yay. Me met the purchasing deadline!
