### ISSUE TITLE
Document feature-based roadmap

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#36]
As we speak with various users, we'll be collecting a list of potential MPD features. We'll use this down the line to derive user stories, prioritize, etc. 

[Documented here](https://docs.google.com/spreadsheets/d/1gNCz63qFpztiuL_JK4aPNnicjCglmATOW1dbpU0wxWk/edit#gid=179231394).

**Comment by zappfyllc** [comment]
Feature Roadmap documented here: https://docs.google.com/drawings/d/1WJSQxt_mNZn1SX1Jrb2VHAIAB0duJEIoT8nT2EeHNao/edit?usp=sharing

**Comment by zappfyllc** [comment]
Feature Roadmap drafted from the initial synthesis of ATD User Interviews and analysis of ATD Knack Applications and the Interim Project Database. @amenity and I discussed documenting the roadmap and future feature-driven requirements (e.g. user stories) in a manner consistent with ATD practices. Moving forward, we will do so but the initial draft will still serve as a guide for initial discussion and roadmap conceptualization.
