### ISSUE TITLE
Design Entity Relationship Diagram

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#37]
We will create a high-level entity relationship diagram based on initial user interviews, scoped requirements, and the Access DB schema.

**Comment by zappfyllc** [comment]
Developed first analysis for checking how often certain data entities are mentioned between Interim Project Database schema and user interviews....not meant to be exhaustive but I figure if an entity isn't mentioned more than once, it's either being referred to by a different name (in which case we can collapse) or perhaps it's specific enough to a workgroup but not necessary for another workgroup: https://docs.google.com/spreadsheets/d/1pDVF6z5tHdtHFqhFTnvROf9FkSgabZbpQxgn53hKz-4/edit?usp=sharing
