### ISSUE TITLE
Learn about Development Review's project tracking workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#39]
Upal (didn't attend) & Nathan A. & Sangeeta & Amber

**Comment by zappfyllc** [comment]
Scheduled initial meeting for 10-31 at 10 am

**Comment by zappfyllc** [comment]
Notes from 10/31 call: https://docs.google.com/document/d/149ASQBiLk7Y_27nmVbnnye2qHPwyWdOJhZoZy4D-4TA/edit?usp=sharing
