### ISSUE TITLE
Learn about Public Works' project tracking workflows

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#40]
[Urban Trails Program](https://www.austintexas.gov/urbantrails)
- Staff contact: Katie W. 

[Safe Routes to School](http://www.austintexas.gov/department/child-safety-program)
- Staff contact: Aleksiina 
- [Notes](https://drive.google.com/open?id=1DfEwo3z3rwNXwTF2XpbRqzulTBt9gIbC7ML_MJmVDgM)

[Sidewalks](http://www.austintexas.gov/sidewalks)
- Staff contact:

**Comment by zappfyllc** [comment]
[2018_11_26 Phases 1 and 2 Master Summary Spreadsheet_working copy - DRAFT (1).xlsx](https://github.com/cityofaustin/atd-mobility-project-database/files/3865637/2018_11_26.Phases.1.and.2.Master.Summary.Spreadsheet_working.copy.-.DRAFT.1.xlsx)

**Comment by amenity** [comment]
Added Sidewalks, @zappfyllc - let's ask Katie and Aleksiina whether that should be a separate meeting.

**Comment by zappfyllc** [comment]
Reached out to Katie W on 12/16 about scheduling for the New Year and never heard back, so changing this as a goal for Sprint 15 to close out this Epic. Will reach out this week and try to schedule ASAP.
