### ISSUE TITLE
Learn about Capital Improvements Projects feature class

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#41]
_The CIP Feature Class initiative is both a set of processes and a set of GIS data that aims to integrate capital improvement project (CIP) information from the eCAPRIS project management database with geographic features from several participating departments._

**Resources**
- CIP Feature Class Wiki - G Drive `/gis/Shared_Projects/CIP_Feature_Class/Documentation/CIP_Feature_Class_Wiki.html`
- _[How to Map Projects](https://cityofaustin.sharepoint.com/sites/CPE/SitePages/How-to-Map-Your-Projects.aspx)_, CPE Sharepoint site

**To do**
- [x] @amenity review CIP docs & take [notes here ](https://docs.google.com/document/d/1oYJnq1UwUtVph-UDPwltZu8K8QuJFA4DAxcc4UePCoA/edit#)
- [x] CIP Tour with @alan-deanda on 2/18/20
- [ ] JD review [CIP tour recording and docs](https://github.com/cityofaustin/atd-mobility-project-database/issues/41#issuecomment-590441232) and add to [notes](https://docs.google.com/document/d/1oYJnq1UwUtVph-UDPwltZu8K8QuJFA4DAxcc4UePCoA/edit#)
- [ ] Follow up with Bryan T., Janny P., Ming-ru C., Karen V. from Public Works with questions and/or meeting

**Comment by amenity** [comment]
@johnclary @jaime-mckeown - Is the CIP feature class something @zappfyllc might be able to access?

**Comment by johnclary** [comment]
@amenity yes. @jaime-mckeown let me know if you need help tracking this down. @alan-deanda is familiar with it.

**Comment by jaime-mckeown** [comment]
@johnclary @alan-deanda I can't find the CIP Feature Class. The Data Inventory says that it's in MAINT, nothing there. It's not in GISDM. I don't want to randomly look through directories since I could possible find an out of date version...

**Comment by jaime-mckeown** [comment]
@johnclary I see that the CIP feature class is available in GISDM. Can I export it to share with @zappfyllc?

**Comment by alan-deanda** [comment]
@jaime-mckeown the  ATD CIP feature class is in MAINT inside the ATD_ADMIN.Structure dataset. I've written [this wiki](https://github.com/cityofaustin/atd-geospatial/wiki/CIP-Digitization) and it includes all I know about ATD's involvement in updating the CIP FC in GISDM.

**Comment by jaime-mckeown** [comment]
@amenity do you want the data that is referred to in the initial comment that is in GISDM or the data that @alan-deanda is referring to that is used to help update the data on GISDM?

**Comment by amenity** [comment]
@jaime-mckeown - thanks for talking this over with me earlier. It sounds like the easiest option is to export file geodatabases for the two CIP datasets on Data Mart and @zappfyllc and I can open them using ArcGIS via Citrix. When you get a chance, will you stick them up [here](https://drive.google.com/drive/folders/11PgHsCh-KgEnputC_O3512cYxNGKvQr-)?

**Comment by jaime-mckeown** [comment]
@amenity I have uploaded a file GDB to the Google Drive with the 2 CIP feature classes.

**Comment by amenity** [comment]
Gracias, @jaime-mckeown 🙏🗺️

**Comment by amenity** [comment]
@amenity - try opening this on your machine ;)

**Comment by zappfyllc** [comment]
@amenity add links to the CIP feature class documentation

**Comment by amenity** [comment]
@zappfyllc - realized that we don't have access to the directory with their documentation on the network drive. Janny also pointed us toward the "[How to Map Projects](https://cityofaustin.sharepoint.com/sites/CPE/SitePages/How-to-Map-Your-Projects.aspx)" portion of the CPE Sharepoint site, which I found very helpful.

**Comment by amenity** [comment]
@zappfyllc 
- [Here is a recording](https://web.microsoftstream.com/video/7fe14736-7e57-41b8-a4c4-4e6d1e26c2ab) of my tour with @alan-deanda. 
- [Here's Alan's documentation](https://github.com/cityofaustin/atd-geospatial/wiki/CIP-Digitization) of the work he does digitizing ATD data for CIP

**Comment by amenity** [comment]
[This presentation](https://drive.google.com/open?id=13IB0S4hrsjgdd7H48VXXAW2GEaYEScR5) has a helpful, albeit 7 year old, high-level summary of the data + process from the perspective of PWD maintainers.
