### ISSUE TITLE
Learn how eCAPRIS is being used to track funding by ATD

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#43]
**Objective** 
See how [eCAPRIS](https://docs.google.com/document/d/1ICBPcJLQrAvXv2JqHIW5fCCDZqOUF_adxTaochMSZc4/edit) is being used to track funding by ATD; talk to Dan D. 

**Participants**

**Agenda**

------
- [x] @zappfyllc log in and explore eCapris
- [x] @amenity schedule meeting
- [x] Meet
- [ ] Create resulting issues

**Comment by zappfyllc** [comment]
@johnclary Who should I set this meeting up with to walkthrough and see eCapris? Is there a login I could use?

**Comment by amenity** [comment]
Emailed CTM to request a read-only account for @zappfyllc so that we can dive into this in Sprint 16.

**Comment by zappfyllc** [comment]
Meeting Notes: https://docs.google.com/document/d/1UmMmy4KnE64ixmHQsg8jp1pfEBg85VwqTWR2wd6EDWg/edit?usp=sharing

**Comment by zappfyllc** [comment]
Added to synthesis document: https://docs.google.com/document/d/1swkNIccJtT5IzdQz_zi4H2LgzhQd3c4iC22Y8SiGOQk/edit?usp=sharing
