### ISSUE TITLE
Investigate Interim Project Database data structure

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#47]

**Comment by zappfyllc** [comment]
Identified questions to help structure conversation with Nathan based on the entities in the Interim Project Database:

1. What are project drivers? Is this owners of a given project? Project Coordination—how is this factored into the loop? 
2. Which entities are actually tied into the GIS integration? What are the unique values used for this integration (identifier, coordinates, etc.)?
3. Schools, Churches fields: would you imagine these potentially being listed in their own table and then related to a given project? Is there value in capturing these as separate entities? Are there other fields/attributes in the Projects table that could be broken out into separate objects?
4. Project Dates/Milestones—explanation please

**Comment by zappfyllc** [comment]
Will update this issue after meeting with Nathan on 1/27

**Comment by zappfyllc** [comment]
Update Data Entity Analysis Spreadsheet + link to compiled notes about Interim Project Database schema

**Comment by zappfyllc** [comment]
https://docs.google.com/spreadsheets/d/1K6ccVQUt4YkUrQPw16ky75S05SluFqZCfWuXQ955DAk/edit?usp=sharing
