### ISSUE TITLE
Investigate ATD's existing Knack apps

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#48]
[App inventory](https://atd.knack.com/dts#applications/)
[General DTS Knack docs](https://github.com/cityofaustin/atd-data-tech/wiki/Knack%3A-Application-Overview)
[ATD's Knack Repos](https://github.com/orgs/cityofaustin/teams/transportation/repositories?utf8=%E2%9C%93&query=knack)

**Comment by zappfyllc** [comment]
Completed emergency analysis of Knack app here: https://github.com/cityofaustin/atd-data-tech/issues/832

Still pending analysis of all Knack apps with access

**Comment by zappfyllc** [comment]
Changed estimate to 3: I have reviewed the list but have not had time to deep dive into the applications using the logins. I would like to directly compare a list of entities from these Knack applications with the Interim Project Database, identify the gaps, and then place entities in different categories (for example: objects/entities that seem central to MPD vs. objects/entities that seem specific to a workgroup vs. objects/entities that appear in Interim Project Database).

**Comment by amenity** [comment]
Going to create a list of MPD-relevant entities in existing Knack apps. @johnclary - should JD focus on these three apps?
- AMD Data Tracker
- Signs & Markings Operations
- Finance

**Comment by johnclary** [comment]
@amenity correct!

**Comment by amenity** [comment]
Going to add columns to the [MPD Data Entity Analysis](https://docs.google.com/spreadsheets/d/1pDVF6z5tHdtHFqhFTnvROf9FkSgabZbpQxgn53hKz-4/edit#gid=0) spreadsheet for each app.

**Comment by zappfyllc** [comment]
@zappfyllc Add columns to the MPD Data Entity Analysis spreadsheet for each app.

**Comment by zappfyllc** [comment]
Columns added to MPD Data Entity Analysis spreadsheet.
