### ISSUE TITLE
Present MPD to the Pedestrian Advisory Council

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#53]
[slides](https://docs.google.com/presentation/d/1351FYBWjOQdTluidYSjH1tEomDHOFTAdK0QjJSsfAzw/edit#slide=id.g7c13fddd9b_0_3)

In September, then-Vice-Chair (now Chair) Adam G submitted [this draft recommendation](https://drive.google.com/open?id=170tT68N85HPOS2G5PtTkH68dn-8gMp8I) for the PAC’s consideration. It was essentially a request that City staff begin compiling/sharing regular updates (e.g. monthly or quarterly) with the PAC regarding recently-implemented pedestrian infra. When I shopped this around to relevant staff (ATSD, area engineers, sidewalk program, etc) to see if they thought this was reasonable/doable, I received feedback that it would be too burdensome of a task to take on voluntarily and would likely require more than just a PAC request (i.e. ACM direction or Council action) to compel staff to compile and share those updates. Then in speaking with John I learned that your team was working on a Mobility Project Database that meet these same needs anyway, eventually. So the PAC postponed consideration of the item until they could receive a briefing from you and understand what info the dashboard will include.

So while they are curious about MPD in general, they are also seeking to understand if it will make their pending request for updates unnecessary/redundant.

**Comment by johnclary** [comment]
@amenity the questions we heard from the Council:

- Have you looked at what other agencies (TXDOT, County, etc) are doing data-wise. Can you integrate with them?
- Do you plan on replacing the other maps and views online? E.g. capital projects explorer?
- Will be able to we tell how much we’re spending on pedestrian infrastructure?
- Comment:  Please retain historical projects that have been completed.
- Can you query years and compare years? There’s been a ramp up of sidewalk spending, but we don’t know how much?
- How are you defining mobility projects?
- Will APD overtime hours be tracked in here?
- Before and after photos?
