### ISSUE TITLE
Learn about Safe Routes to School project tracking workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#55]
[Safe Routes to School](http://www.austintexas.gov/department/child-safety-program)
- Staff contact: Aleksiina 
- [Notes](https://docs.google.com/document/d/1Hl_Rok5c_cn46t0kySgU-3MRl_Z63Emn9yhcpBVW7y0/edit#)

**Comment by zappfyllc** [comment]
Safe Routes to Schools takeaways updated in Learning Synthesis document here: https://drive.google.com/file/d/1wZc4qUWmBI4yxi2Wa5cfBz-hdaUQ24Tx/view?usp=sharing
