### ISSUE TITLE
Learn about Urban Trails project tracking workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#56]
[Urban Trails Program](https://www.austintexas.gov/urbantrails)
- Staff contact: Katie W.

**Comment by zappfyllc** [comment]
@amenity I reached out to Katie after checking her availability in Outlook and it looks like 2020 may have to be the meeting here but I'll try to get it scheduled so we don't have to coordinate after the break.

**Comment by amenity** [comment]
@zappfyllc - gotcha, thanks. Perhaps Colleen (#57) or Caitlin (#19) has time to meet before break?

**Comment by zappfyllc** [comment]
Reached out again on 1/17 (original email sent 12/16, no response).

**Comment by zappfyllc** [comment]
Agreed with @amenity to postpone for now instead of badgering for a response. Moving this to the Backlog for now.

**Comment by zappfyllc** [comment]
@amenity Nathan has yet to integrate with Urban Trails so he was not as familiar with their needs for the Interim Project Database. They are on the list though.
