### ISSUE TITLE
Learn about Sidewalks Program's project tracking workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#57]
_From Carolynn Calabrese, PIO at PWD on 10/14/2019_

> _Our Sidewalks team works hard to keep [this map](https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=02eecf190f5241f19f92492d63ba5ce2) updated as best as possible, and it's really helpful that it shows individual projects rather than groups of projects the way that Capital Projects Explorer does. The only things I wish I could see that I can't are completed projects (which understandably would be a huge lift to keep track of in the long haul, as projects can be pretty small and are always going on!) and to easily be able to pull all the sidewalks with 2016 Mobility Bond-funded work at one time. (While I'd say most of our current sidewalks projects receive at least some 2016 Mobility Bond funding, a few, like Neighborhood Partnering Program projects or ones that might be totally funded by quarter cent funds, grants, etc might not be so it takes a little more legwork to produce stats for collateral)._

- [Sidewalks Program map](https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=02eecf190f5241f19f92492d63ba5ce2)
- Staff contact: Coleen G.

**Comment by zappfyllc** [comment]
@amenity suggested a call in an email on 12/13. If that doesn't happen, I'll at least take a look prior to the break and will comment on the map referenced above and how requirements from Safe Routes to Schools and other ATD workgroups may overlap.

**Comment by zappfyllc** [comment]
Call notes for 12/11 meeting with Coleen: https://docs.google.com/document/d/15wjl5G7JVMDjRcX7LFibIlU4ncT3Uch9RkYemwlHgHs/edit?usp=sharing
