### ISSUE TITLE
Discuss MPD technical approach 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#64]
- Review data model and system architecture 
- Creating an MPD API
- Modular approach to staff-facing applications; some could be in Knack, others elsewhere?
...

An "MVP" for testing and iteration might include:
**Data pipelines+database that standardize+centralize mobility project data from various sources such as** 
- AMD Data Tracker (possibly modifying and/or extending Data Tracker in small ways)
- Traffic Engineering (input through a new Knack App OR some sort of other form tool)
- E-Capris 

**Pull data from :point_up_2: into various visualization/analysis platforms such as**
- AGOL, Power BI, Insights
- Capital Improvement Projects layer 
- Custom map/dashboard (Mobility Project Viewer) 

---
- [x] Schedule main meeting with DTS team
- [x] Fill out [agenda doc](https://docs.google.com/document/d/1kXgyOa7aS6u-gOttv-f2zZQQQmk8nrn7oERM2FT8a5I/edit#heading=h.9y2xzfo6m7nc)
- [x] Meet
- [ ] Create resulting issues

**Comment by zappfyllc** [comment]
@amenity Schedule this meeting near the end of Sprint 18, so that @zappfyllc can complete documentation of Interim Project Database schema, Data Entity Analysis spreadsheet, and partial completion of Entity Relationship Diagram.

**Comment by zappfyllc** [comment]
@amenity can you please schedule a meeting between @johnclary and us prior to this call to review the diagram and align on key points before getting with the rest of the team? 30 minutes should be fine. I'll update the description to include this. My apologies if it should be a separate issue, but figured it could be tacked on here.

**Comment by amenity** [comment]
Spoke with @zappfyllc and agree that an additional meeting won't be necessary. ;)

**Comment by amenity** [comment]
@zappfyllc - notes for you to review [here](https://docs.google.com/document/d/1kXgyOa7aS6u-gOttv-f2zZQQQmk8nrn7oERM2FT8a5I/edit#heading=h.9y2xzfo6m7nc). 

@mateoclarke @johnclary @sergiogcx - feel free to add/amend ☝️
