### ISSUE TITLE
Sprint 17 Sprint Review

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#65]
_Tuesday, 2/11/20_

[Presentation Deck](https://docs.google.com/presentation/d/1B26krxCa8o8EwnfxNf1MAw57eX_JKZm7rquyaouontE/edit#slide=id.g1f0339f18f_3_0)

[Recording](https://web.microsoftstream.com/video/052ffedd-27de-47dd-87cf-63fa8db75b75).

**Comment by amenity** [comment]
Notes: 
  ### Success Criteria review

  **Success Criteria # 2 & # 3** 
  - "Transparency" is important to define — there will be a lot of data that isn't fit for public consumption - NW
    - Don't want to inhibit data entry because users are scared of people seeing the data
  - Should have a workshop on data propagation - status fields that are precise - e.g. a "public status" field might not always be propagated to public - NW
  - There will be other viewers and dashboards for public; goal now is to make sure the data model supports the segmentation of internal-only and public-facing data. Mobility Project Viewer - NW

**Success Criteria # 5**
  - "Mobility portfolio" instead of "Department-wide" - NW
  - Not as useful if it's just ATD? How will I get Austin Water info in here? - Ryan, ROW
  - MPD will be the record of source for mobility planning, we don't have anything for that now. Data from MPD will go into other systems such as IMMPACT. Might be as small as work that Robin O does, eg where are LPIs active? - NW

  

  ### System Context
  NW:
  - MPD includes the ability to edit the geospatial attributes of a system
  - Operationally-funded items won't have be in eCapris, won't have CIP ID
  - Once there is a CIP ID, any edits to it should propoagate out (nightly) to CIP feature class 
  - There will be a lot of data that is only consumed internally, potential projects 
  - What's labeled as "Mobility Project Viewer" could be Mobility Project Viewer - Internal
  - Traffic Engineering and Active Transportation don't need their own "Apps" since they're moving other groups' work forward, not tracking assets and infrastructure

**Comment by johnclary** [comment]
thanks @amenity. as you can guess i'm strongly opposed to a an "internal" (aka behind a login) dashboard for data that is not PII. we need to default to open. we cannot start work on any viewer until we resolve this question. i'll lead the charge on that.
