### ISSUE TITLE
Spike: Mobility Project Editor inline tabular editing

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#69]
Many Mobility Project Database users will be transitioning to MPD from a spreadsheet-based project tracking workflow where they can quickly add data across multiple line items, see live updates, etc. Can we reproduce this experience in Mobility Project Editor?

**Comment by sergiogcx** [comment]
Mateo discovered this framework: https://codesandbox.io/s/tannerlinsleyreact-table-kitchen-sink-d9yz3

**Comment by sergiogcx** [comment]
For my part, I have worked with this framework before, and I have the highest regards for it:
https://handsontable.com/examples?manual-resize&manual-move&conditional-formatting&context-menu&filters&dropdown-menu&headers

**Comment by amenity** [comment]
Oooh! 😻 😻
