### ISSUE TITLE
Spike: MPD Access DB integration & ETL

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#70]
Per [this discussion](https://docs.google.com/document/d/1kXgyOa7aS6u-gOttv-f2zZQQQmk8nrn7oERM2FT8a5I/edit#), it would be good to determine what it will take to get data out of the Access DB and into Hasura, whether this is a one-way, one-time migration with an ETL or a standing connection that would enable us to transition users/functionality in phases from the Interim Project DB.

**Comment by sergiogcx** [comment]
Not related, but Surbhi found a great resource for loading data into Socrata (if we end up using it):
https://support.socrata.com/hc/en-us/articles/360033395434-Gateway-Overview
