### ISSUE TITLE
Stakeholder kickoff meeting

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobility-project-database#8]
- [Slides](https://docs.google.com/presentation/d/1O2rFrL1aNCEcxzsACuyEdyzSfzvTE9mL6lGjlwJei3k/edit#slide=id.g5df29b1aef_0_153)
- [Agenda](https://docs.google.com/document/d/1eQVC9d-KPu-7wJycbv4uZNHpepWZ6nCJm2zZop5YQ-E/edit#heading=h.ps8ktjan7nis)
- [Photos](https://drive.google.com/drive/folders/1RPHQXPR1hQM9W2RcAU1lX4sSWpGzAq_F)

**Comment by johnclary** [comment]
Notes from presentation/discussion:

- Sean: calculating the right “quantities” [in the Access DB] has been very challenging
- Kirk: We need to draw a line between projects and funding sources
- Nathan suggested “Mobility Activities” instead of “Infrastructure”
- Upal + Amica: we want to be contribute to design + research

**Comment by amenity** [comment]
Attendees:
 - John Clary
 - Cole Kitten, Systems Development
 - Jen Duthie, Arterial Management
 - Nathan Wilkes, Active Transportation
 - Joel Meyer, Vision Zero
 - Nathan Aubert, Transportation Engineering
 - Sean Corcoran, Active Transportation
 - Peggy MacCallum, Finance
 - Upal Barua, Transportation Engineering
 - Janae Spence, Urban Trails
 - Kirk Scanlon, SMART Mobility
 - Amica Bose, Traffic Engineering

???
Bollich, Eric <Eric.Bollich@austintexas.gov>
Chapman, Aleksiina <Aleksiina.Chapman@austintexas.gov>
Miller, Liane <Liane.Miller@austintexas.gov>
Scanlon, Kirk <Kirk.Scanlon@austintexas.gov>
Wettick, Katie <Katie.Wettick@austintexas.gov>
Haithcock, Carly <Carly.Haithcock@austintexas.gov>
Quarles, Neil <Neil.Quarles@austintexas.gov>
Schofield, Mike <Mike.Schofield@austintexas.gov>
Willingham, Christina <Christina.Willingham@austintexas.gov>
